services:
  mysql:
    image: mysql:8.0
    restart: always
    # tty: true
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
  frontend:
    image: toversus/otel-demo:frontend
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - REACT_APP_USER_URL=http://user:8080
      - REACT_APP_PAYMENT_URL=http://payment:8081
      - REACT_APP_ORDER_URL=http://order:8082
    depends_on:
      - user
      - payment
      - order
  user:
    image: toversus/otel-demo:backend
    command: users
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - USER_ADDR=0.0.0.0:8080
      - SQL_USER=root
      - SQL_HOST=mysql:3306
      - SQL_DB=demo
      - OTEL_ADDR=otel-collector:4317
    depends_on:
      - mysql
  payment:
    image: toversus/otel-demo:backend
    command: payment
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - USER_URL=http://user:8080
      - PAYMENT_ADDR=0.0.0.0:8081
      - OTEL_ADDR=otel-collector:4317
    depends_on:
      - mysql
  order:
    image: toversus/otel-demo:backend
    command: order
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - USER_URL=http://user:8080
      - ORDER_ADDR=0.0.0.0:8082
      - SQL_USER=root
      - SQL_HOST=mysql:3306
      - SQL_DB=demo
      - OTEL_ADDR=otel-collector:4317
    depends_on:
      - mysql

  otel-collector:
    image: otel/opentelemetry-collector:0.80.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
  tempo:
    image: grafana/tempo:2.1.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"   # otlp grpc
      - "4318"   # otlp http
      - "9411"   # zipkin
  prometheus:
    image: prom/prometheus:v2.44.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.0.0
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
