{{- if and .Values.global.gateway.enabled .Values.frontend.backendPolicy.enabled -}}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "otel-demo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  default:
    securityPolicy: {{ .Values.frontend.backendPolicy.securityPolicy }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "otel-demo.frontend.fullname" . }}
{{- end }}
