apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "otel-demo.frontend.fullname" . }}-config-js"
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    // Application URLs
    var USER_URL = '{{ tpl .Values.frontend.usersUrl . }}'
    var PAYMENT_URL = '{{ tpl .Values.frontend.paymentUrl . }}'
    var ORDER_URL = '{{ tpl .Values.frontend.orderUrl . }}'
