apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otel-demo.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/frontend/nginx-conf.yaml") . | sha256sum }}
        checksum/config-js: {{ include (print $.Template.BasePath "/frontend/config-js.yaml") . | sha256sum }}
      {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otel-demo.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otel-demo.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "otel-demo.frontend.name" . }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository | default .Values.global.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          {{- with (concat .Values.global.env .Values.frontend.extraEnv) }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: config-js
              mountPath: /usr/share/nginx/html/static/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: "{{ include "otel-demo.frontend.fullname" . }}-nginx-conf"
            items:
            - key: nginx.conf
              path: default.conf
        - name: config-js
          configMap:
            name: "{{ include "otel-demo.frontend.fullname" . }}-config-js"
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
