apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otel-demo.frontend.selectorLabels" . | nindent 4 }}
