{{- if .Values.users.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-demo.users.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.users.labels" . | nindent 4 }}
  {{- with .Values.users.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
