name: Image

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/toversus/otel-demo:frontend
        file: frontend/Dockerfile
        cache-from: type=registry,ref=ghcr.io/toversus/otel-demo:frontend
        cache-to: type=inline
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/toversus/otel-demo:backend
        cache-from: type=registry,ref=ghcr.io/toversus/otel-demo:backend
        cache-to: type=inline
