{{- if .Values.order.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otel-demo.order.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.order.labels" . | nindent 4 }}
  {{- with .Values.order.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
