apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.order.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.order.labels" . | nindent 4 }}
spec:
  type: {{ .Values.order.service.type }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otel-demo.order.selectorLabels" . | nindent 4 }}
